### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by krazykira**
Added Twitter Helper to SDK Section 
Added CuXtom Cam For Google Glass to Android Wear Section

### CODE REVIEW

**Comment by krazykira** [comment]
Please let me know once you merge it back :+1:

**Comment by krazykira** [comment]
@snowdream @Aexyn  can you guys please let me know once you merge this :)

**Comment by krazykira** [comment]
@snowdream  Why reject this ?

**Comment by snowdream** [comment]
it is better to have more users.

**Comment by krazykira** [comment]
What do you mean ?

**Pull request closed without merging**
